[package]
name = "image-maker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ts-format = { path = "../ts-format" }
tianmu-fs = { path = "../tianmu-fs" }